Convert the transactions Data Frame to contain dicts
To fix AttributeError: 'dict' object has no attribute 'dtype'

I don't understand what happens here. It works with max amount and chunk
size both set to 3000, but we get the above error when they are set to
5000.